### ISSUE TITLE
DefaultEvent is "Click"

### ISSUE THREAD

**Issue by Deantwo** [m66n/ipaddresscontrollib#10]
Double clicking the control in the designer generates a `private void ipAddressControl1_Click(object sender, EventArgs e)` method. This doesn't make much sense.

Found the answer to it here: http://stackoverflow.com/a/22601554/5815327

I guess `[DefaultEvent("TextChanged")]` would make the most sense.

**Comment by m66n** [comment]
I agree that `TextChanged` should be the default event. I added that to the VS2015 project.
