### ISSUE TITLE
Can you add this library to Nuget?

### ISSUE THREAD

**Issue by stamepicmorg** [m66n/ipaddresscontrollib#11]
[NuGet](https://www.nuget.org/) is the package manager for the Microsoft development platform including .NET. The NuGet client tools provide the ability to produce and consume packages. The NuGet Gallery is the central package repository used by all package authors and consumers.

And users can install it  directly from visual studio 2013\2015.

Thanks.

**Comment by m66n** [comment]
[It looks like somebody has already done that.] (https://www.nuget.org/packages/IPAddressControl/)

**Comment by stamepicmorg** [comment]
but there version is too old (2013-11-14)..

**Comment by m66n** [comment]
Tell them that.

**Comment by m66n** [comment]
[I put something up] (https://www.nuget.org/packages/IPAddressControlLib/1.3.5942.27121) that has a VS2015 release build of the project. It doesn't seem to conflict with the other project.

**Comment by m66n** [comment]
Adding the assembly from NuGet doesn't add the control to the designer toolbox. Other control authors report the same issue with no obvious solution, other than to add a TextBox control to a form in the designer and then change it to an IPAddressControl in the code editor. That's far from ideal.
