### ISSUE TITLE
.NETFramework,Version=v4.5

### ISSUE THREAD

**Issue by Jaom** [m66n/ipaddresscontrollib#14]
> Could not install package 'IPAddressControlLib 1.3.5942.27121'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by m66n** [comment]
You're better off just downloading the source for whichever version of Visual Studio you're using, and building it as part of your project. The file from NuGet doesn't add the control to the Visual Studio form design toolbox (or at least it doesn't for me.) I'll look into adding multiple versions into the Nuget file, but it will take a few days.

**Comment by Jaom** [comment]
Somehow I got it working. I'd tell how but I was busy with something and I didn't notice how that happened... (obviously I needed to add it to the the toolbox after it succeeded with the NuGet Installation).
