### ISSUE TITLE
Click zone

### ISSUE THREAD

**Issue by smidlik** [m66n/ipaddresscontrollib#19]
If you click between dots and number it does do nothink. For select number you must click directly on number. Can by zone for clicking expanded for whole number box.

**Comment by m66n** [comment]
I'll look into it. Give me a couple of days.

**Comment by m66n** [comment]
I've checked in some code that should handle mouse clicks properly. Let me know if it works for you and I'll close this. Thanks for raising this issue.

**Comment by smidlik** [comment]
Yeah, its work well. Thank you very much.
