### ISSUE TITLE
NuGet Confusion

### ISSUE THREAD

**Issue by Deantwo** [m66n/ipaddresscontrollib#22]
I just noticed that I am using the wrong NuGet in one of my projects.

I was seemingly using this: https://www.nuget.org/packages/IPAddressControl

It looks like it is a much older version of this project, and I can't seem to find IPAddressControlLib's NuGet in the VisualStudio search feature at all.

Maybe https://www.nuget.org/packages/IPAddressControlLib and https://www.nuget.org/packages/IPAddressControl should be merged or something? I don't know how NuGet handles stuff like this.

Also it looks like the NuGet shield is broken for some reason, is https://www.nuget.org/packages/IPAddressControlLib out of order or something?
![image](https://user-images.githubusercontent.com/2676134/131995352-593e37f2-fc2b-4785-a32d-6d0020de1cfb.png)

**Comment by Deantwo** [comment]
Oh, https://www.nuget.org/packages/IPAddressControlLib is unlisted? Why?
![image](https://user-images.githubusercontent.com/2676134/132012033-021ecb16-5dcb-4d5d-8c79-1e0fc5089c51.png)

**Comment by m66n** [comment]
The package is deprecated. NuGet has no value. Feel free to create your own package.
