### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by dcormier** [m66n/ipaddresscontrollib#8]
I am not a lawyer, but looking at [the license](/m66n/ipaddresscontrollib/blob/master/VS2015/IPAddressControlLib/COPYING) for this library it reads like I have to include that full notice, which would then tell my users that they can make copies of and sell "the 'Software'" (my software).

Is this what was intended?

**Comment by m66n** [comment]
[COPYING] (https://raw.githubusercontent.com/m66n/ipaddresscontrollib/master/VS2015/IPAddressControlLib/COPYING) contains the text of the [MIT license] (http://opensource.org/licenses/MIT). I am not a lawyer either, but I think the license [only applies to distribution of the source code and not any binary form] (http://programmers.stackexchange.com/questions/255227/meaning-of-mit-license). I believe you are free to do whatever you want with the code except redistribute it in source form without that license file. I also believe you are not required to distribute any source code, either yours or mine, and that this license does not interfere with any license you choose for your software.
